language: go
go:
    - tip

script:
    - go get github.com/gin-gonic/gin
    - go get github.com/jinzhu/gorm
    - go get github.com/jinzhu/gorm/dialects/sqlite
    - go get github.com/caTUstrophy/backend/db
    - go build

notifications:
  email:
    on_success: change
    on_failure: always